runtime: java11
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/mlal777/test.git#d854dca987c29e0d68c03e35d50d06585716b819'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
